### ISSUE TITLE
Do you have any plans to support Wax cloud wallet?

### ISSUE THREAD

**Issue by boivin123** [benjiewheeler/farmers-bot#2]
I understand that Wax Cloud Wallet does not provide us with a private key. But it can retrieve pubKeys. Do you think there is a way to get pubKeys into the transaction flow?

Thank.

**Comment by benjiewheeler** [comment]
No, signing transactions requires the private key, which WCW won't let you have. so no it's not possible without the private key.

Also interacting with WAX Cloud Wallet is not possible without a browser (afaik)
